AspNetCoreIdentityCourse.IdentityApp/Controllers/AccountController.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AspNetCoreIdentityCourse.IdentityApp.Controllers;

[Route("api/[controller]")]
[ApiController]
public class AccountController : ControllerBase
{
    private readonly SignInManager<User> _signInManager;

    public AccountController(SignInManager<User> signInManager)
    {
        _signInManager = signInManager;
    }

    public async Task<IActionResult> ExternalLoginCallback()
    {
        var loginInfo = await _signInManager.GetExternalLoginInfoAsync();
        var emailClaim = loginInfo!.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
        var userClaim = loginInfo!.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

        if (emailClaim is not null && userClaim is not null)
        {
            var user = new User { Email = emailClaim.Value, UserName = userClaim.Value, Department = "None", Position = "None" };
            await _signInManager.SignInAsync(user, false);
        }

        return RedirectToPage("/Index");
    }
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/ConfirmEmail.cshtml.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

public class ConfirmEmailModel : PageModel
{
    private readonly UserManager<User> _userManager;

    [BindProperty]
    public string Message { get; set; } = "";

    public ConfirmEmailModel(UserManager<User> userManager)
    {
        _userManager = userManager;
    }

    public async Task<IActionResult> OnGetAsync(string userId, string token)
    {
        var user = await _userManager.FindByIdAsync(userId);

        if (user is not null)
        {
            var result = await _userManager.ConfirmEmailAsync(user, token);

            if (result.Succeeded)
            {
                Message = "Email address is successfully confirm, now you can try to login.";
                return Page();
            }
        }

        Message = "Failed to validate email.";
        return Page();
    }
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/Login.cshtml.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

public class LoginModel : PageModel
{
    private readonly SignInManager<User> _signInManager;

    public LoginModel(SignInManager<User> signInManager)
    {
        _signInManager = signInManager;
    }

    [BindProperty]
    public CredentialVm Credential { get; set; } = new();

    [BindProperty]
    public IEnumerable<AuthenticationScheme> ExternalLoginProviders { get; set; } = new List<AuthenticationScheme>();

    public async Task OnGetAsync()
    {
        ExternalLoginProviders = await _signInManager.GetExternalAuthenticationSchemesAsync();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var result = await _signInManager.PasswordSignInAsync(
            Credential.Email, Credential.Password, Credential.RememberMe, false);

        if (result.Succeeded)
        {
            return RedirectToPage("/Index");
        }
        else
        {
            if (result.RequiresTwoFactor)
            {
                return RedirectToPage("/Account/LoginTwoFactorWithAuthenticator", new { RememberMe = Credential.RememberMe });
            }
            else if (result.IsLockedOut)
            {
                ModelState.AddModelError("Login", "You are locked out.");
            }
            else
            {
                ModelState.AddModelError("Login", "Failed to login.");
            }

            return Page();
        }
    }

    public IActionResult OnPostLoginExternally(string provider)
    {
        var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, null);
        properties.RedirectUri = Url.Action("ExternalLoginCallback", "Account");

        return Challenge(properties, provider);
    }
}

public class CredentialVm
{
    [Required]
    public string Email { get; set; } = "";

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; } = "";

    [Display(Name = "Remember Me")]
    public bool RememberMe { get; set; }
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/LoginTwoFactor.cshtml.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using AspNetCoreIdentityCourse.IdentityApp.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

public class LoginTwoFactorModel : PageModel
{
    private readonly UserManager<User> _userManager;
    private readonly IEmailService _emailService;
    private readonly SignInManager<User> _signInManager;

    [BindProperty]
    public Email2FAVm Email2FA { get; set; } = new();

    public LoginTwoFactorModel(
        UserManager<User> userManager, 
        IEmailService emailService, 
        SignInManager<User> signInManager)
    {
        _userManager = userManager;
        _emailService = emailService;
        _signInManager = signInManager;
    }

    public async Task<IActionResult> OnGetAsync(string email, bool rememberMe)
    {
        Email2FA.RememberMe = rememberMe;

        var user = await _userManager.FindByEmailAsync(email);

        var token = await _userManager.GenerateTwoFactorTokenAsync(user!, "Email");

        await _emailService.SendAsync("noreply@identityapp.com", email, 
            "My Web App's 2FA", 
            $"Pease use this code as the 2FA: {token}");

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid) return Page();

        var result = await _signInManager.TwoFactorSignInAsync(
            "Email", Email2FA.SecurityCode, Email2FA.RememberMe, false);

        if (result.Succeeded)
        {
            return RedirectToPage("/Index");
        }
        else
        {
            if (result.IsLockedOut)
            {
                ModelState.AddModelError("Login2FA", "You are locked out.");
            }
            else
            {
                ModelState.AddModelError("Login2FA", "Failed to login.");
            }

            return Page();
        }
    }
}

public class Email2FAVm
{
    [Required]
    [DisplayName("Security Code")]
    public string SecurityCode { get; set; } = "";

    public bool RememberMe { get; set; }
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Identity;
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

public class LoginTwoFactorWithAuthenticatorModel : PageModel
{
    private readonly SignInManager<User> _signInManager;

    public LoginTwoFactorWithAuthenticatorModel(SignInManager<User> signInManager)
    {
        _signInManager = signInManager;
    }

    [BindProperty]
    public Authenticator2FAVm Authenticator2FA { get; set; } = new();

    public void OnGet(bool rememberMe)
    {
        Authenticator2FA.SecurityCode = "";
        Authenticator2FA.RememberMe = rememberMe;
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid) return Page();

        var result = await _signInManager.TwoFactorAuthenticatorSignInAsync(
            Authenticator2FA.SecurityCode, Authenticator2FA.RememberMe, false);

        if (result.Succeeded)
        {
            return RedirectToPage("/Index");
        }
        else
        {
            if (result.IsLockedOut)
            {
                ModelState.AddModelError("Authenticator2FA", "You are locked out.");
            }
            else
            {
                ModelState.AddModelError("Authenticator2FA", "Failed to login.");
            }

            return Page();
        }
    }
}

public class Authenticator2FAVm
{
    [Required]
    [DisplayName("Security Code")]
    public string SecurityCode { get; set; } = "";

    public bool RememberMe { get; set; }
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/Logout.cshtml.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

public class LogoutModel : PageModel
{
    private readonly SignInManager<User> _signInManager;

    public LogoutModel(SignInManager<User> signInManager)
    {
        _signInManager = signInManager;
    }

    public async Task<IActionResult> OnPostAsync()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("/Account/Login");
    }
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/MFAAuthenticatorSetup.cshtml.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QRCoder;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

[Authorize]
public class MFAAuthenticatorSetupModel : PageModel
{
    private readonly UserManager<User> _userManager;

    [BindProperty]
    public SetupMFAVm SetupMFA { get; set; } = new();

    [BindProperty]
    public bool Succeeded { get; set; } = false;

    public MFAAuthenticatorSetupModel(UserManager<User> userManager)
    {
        _userManager = userManager;
    }

    public async Task OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);

        await _userManager.ResetAuthenticatorKeyAsync(user!);

        var key = await _userManager.GetAuthenticatorKeyAsync(user!);

        SetupMFA.Key = key!;
        SetupMFA.QRCodeBytes = GenerateQRCodeBytes("AspNetCoreIdentityCourse", key!, user!.Email!);
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid) return Page();

        var user = await _userManager.GetUserAsync(User);

        if (await _userManager.VerifyTwoFactorTokenAsync(
            user!, _userManager.Options.Tokens.AuthenticatorTokenProvider, SetupMFA.SecurityCode))
        {
            await _userManager.SetTwoFactorEnabledAsync(user!, true);
            Succeeded = true;
        }
        else
        {
            ModelState.AddModelError("AuthenticatorSetup", "Something went wrong with authenticator setup.");
        }

        return Page();
    }

    private byte[] GenerateQRCodeBytes(string provider, string key, string userEmail)
    {
        var qrCodeGenerator = new QRCodeGenerator();

        var qrCodeData = qrCodeGenerator.CreateQrCode(
            $"otpauth://totp/{provider}:{userEmail}?secret={key}&issuer={provider}",
            QRCodeGenerator.ECCLevel.Q);

        var qrCode = new PngByteQRCode(qrCodeData);
        var qrCodeImage = qrCode.GetGraphic(20);
        return qrCodeImage;
    }
}

public class SetupMFAVm
{
    public string Key { get; set; } = "";

    [Required]
    [DisplayName("Security Code")]
    public string SecurityCode { get; set; } = "";

    public byte[] QRCodeBytes { get; set; } = Array.Empty<byte>();
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/Register.cshtml.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using AspNetCoreIdentityCourse.IdentityApp.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

public class RegisterModel : PageModel
{
    private readonly UserManager<User> _userManager;
    private readonly IEmailService _emailService;

    public RegisterModel(UserManager<User> userManager, IEmailService emailService)
    {
        _userManager = userManager;
        _emailService = emailService;
    }

    [BindProperty]
    public RegisterVm RegisterVm { get; set; } = new();

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid) return Page();

        var user = new User
        {
            Email = RegisterVm.Email,
            UserName = RegisterVm.Email,
            Department = RegisterVm.Department,
            Position = RegisterVm.Position,
        };

        var aliasClaim = new Claim("Alias", RegisterVm.Alias);

        var result = await _userManager.CreateAsync(user, RegisterVm.Password);

        if (result.Succeeded)
        {
            await _userManager.AddClaimAsync(user, aliasClaim);

            var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            var link = Url.PageLink(pageName: "/Account/ConfirmEmail", values: new { userId = user.Id, token });
            
            await _emailService.SendAsync("noreply@identityapp.com", user.Email, 
                "Please confirm your email", 
                $"Please click on this link to confirm your email address: {link}");

            return RedirectToPage("/Account/Login");
        }
        else
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("Register", error.Description);
            }

            return Page();
        }
    }
}

public class RegisterVm
{
    [Required]
    [EmailAddress(ErrorMessage = "Invalid email address")]
    public string Email { get; set; } = "";

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; } = "";

    [Required]
    public string Department { get; set; } = "";

    [Required]
    public string Position { get; set; } = "";

    [Required]
    public string Alias { get; set; } = "";
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/UserProfile.cshtml.cs
using AspNetCoreIdentityCourse.IdentityApp.Data.Account;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace AspNetCoreIdentityCourse.IdentityApp.Pages.Account;

[Authorize]
public class UserProfileModel : PageModel
{
    private readonly UserManager<User> _userManager;

    [BindProperty]
    public UserProfileViewModel UserProfile { get; set; } = new();

    [BindProperty]
    public string? SuccessMessage { get; set; } = "";

    public UserProfileModel(UserManager<User> userManager)
    {
        _userManager = userManager;
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var (user, aliasClaim) = await GetUserAndAliasClaimAsync();

        UserProfile.Email = User.Identity?.Name ?? "";
        UserProfile.Department = user.Department;
        UserProfile.Position = user.Position;
        UserProfile.Alias = aliasClaim?.Value ?? "";

        SuccessMessage = "";

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid) return Page();

        var (user, aliasClaim) = await GetUserAndAliasClaimAsync();

        user.Department = UserProfile.Department;
        user.Position = UserProfile.Position;

        try
        {
            await _userManager.UpdateAsync(user);
            await _userManager.ReplaceClaimAsync(user, aliasClaim, new Claim(aliasClaim.Type, UserProfile.Alias));
            SuccessMessage = "The user profile is saved successfully";
        }
        catch
        {
            ModelState.AddModelError("UserProfile", "Error occurred when saving user profile.");
        }

        return Page();
    }

    private async Task<(User, Claim)> GetUserAndAliasClaimAsync()
    {
        var user = await _userManager.FindByNameAsync(User.Identity?.Name ?? "");
        var claims = await _userManager.GetClaimsAsync(user!);
        var aliasClaim = claims.First(x => x.Type == "Alias");
        return (user!, aliasClaim);
    }
}

public class UserProfileViewModel
{
    [Required]
    public string Email { get; set; } = "";

    [Required]
    public string Department { get; set; } = "";

    [Required]
    public string Position { get; set; } = "";

    [Required]
    public string Alias { get; set; } = "";
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/ConfirmEmail.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.ConfirmEmailModel
@{
}

<p>
    @Model.Message
</p>

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/Login.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.LoginModel
@{
}

<p>
    <h3>User Login</h3>
</p>

<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="Credential.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="Credential.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Email"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="Credential.Password"></label>
            </div>
            <div class="col">
                <input type="password" asp-for="Credential.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Credential.Password"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <input type="checkbox" asp-for="Credential.RememberMe" class="form-check-input" />
                <label class="form-check-label" asp-for="Credential.RememberMe"></label>
            </div>
            <div class="col">
            </div>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Login" />
            </div>
            <div class="col">
                <a class="btn btn-link" href="/Account/Register">Register</a>
            </div>
        </div>
        <br />
        <p>
            Social Media Logins:
            <div class="form-group">
                @foreach (var provider in Model.ExternalLoginProviders)
                {
                    <button type="submit" asp-page-handler="LoginExternally" name="provider" 
                            value="@provider.Name" class="btn btn-primary">
                        Login with @provider.DisplayName
                    </button>
                }
            </div>
        </p>
    </form>
</div>

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/LoginTwoFactor.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.LoginTwoFactorModel
@{
}

<p>
    <h3>Please enter the Code from your email:</h3>
</p>

<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="Email2FA.SecurityCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="Email2FA.SecurityCode" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Email2FA.SecurityCode"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="Email2FA.RememberMe" />
            </div>
        </div>
    </form>
</div>

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.LoginTwoFactorWithAuthenticatorModel
@{
}

<p>
    <h3>Please enter the Code from your authenticator app:</h3>
</p>

<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="Authenticator2FA.SecurityCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="Authenticator2FA.SecurityCode" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="Authenticator2FA.SecurityCode"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="Authenticator2FA.RememberMe" />
            </div>
        </div>
    </form>
</div>

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/Logout.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.LogoutModel
@{
}

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/MFAAuthenticatorSetup.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.MFAAuthenticatorSetupModel
@{
}

<h3>Step 1:</h3>
<p>
    Please scan the QR Code or enter the key to your authenticator app:
</p>
<p>
    <img src="@string.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.SetupMFA.QRCodeBytes))" width="300" height="300" />
</p>
<br />
<p>
    @Model.SetupMFA.Key
</p>
<br />

<h3>Step 2:</h3>
<p>
    Please enter the code from your authenticator app:
</p>
<form method="post">
    @if (Model.Succeeded)
    {
        <div class="alert alert-success">
            The authenticator is successfully setup.
        </div>
    }
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="input-group row mb-3">
        <div class="col-2">
            <label asp-for="SetupMFA.SecurityCode"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="SetupMFA.SecurityCode" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="SetupMFA.SecurityCode"></span>
    </div>
    <div class="input-group row mb-3">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Verify" />
        </div>
        <div class="col">
            <input type="hidden" asp-for="SetupMFA.Key" />
            <input type="hidden" asp-for="SetupMFA.QRCodeBytes" />
        </div>
    </div>
</form>

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/Register.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.RegisterModel
@{
}

<p>
    <h3>User Registration</h3>
</p>

<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="RegisterVm.Email"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterVm.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterVm.Email"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="RegisterVm.Password"></label>
            </div>
            <div class="col">
                <input type="password" asp-for="RegisterVm.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterVm.Password"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="RegisterVm.Department"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterVm.Department" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterVm.Department"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="RegisterVm.Position"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterVm.Position" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterVm.Position"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <label asp-for="RegisterVm.Alias"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="RegisterVm.Alias" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterVm.Alias"></span>
        </div>
        <div class="input-group row mb-3">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Register" />
            </div>
            <div class="col">
            </div>
        </div>
    </form>
</div>

AspNetCoreIdentityCourse.IdentityApp/Pages/Account/UserProfile.cshtml
@page
@model AspNetCoreIdentityCourse.IdentityApp.Pages.Account.UserProfileModel
@{
}

<form method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="input-group row mb-3">
        <div class="col-2">
            <label asp-for="UserProfile.Email"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="UserProfile.Email" class="form-control" readonly />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Email"></span>
    </div>
    <div class="input-group row mb-3">
        <div class="col-2">
            <label asp-for="UserProfile.Department"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="UserProfile.Department" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Department"></span>
    </div>
    <div class="input-group row mb-3">
        <div class="col-2">
            <label asp-for="UserProfile.Position"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="UserProfile.Position" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Position"></span>
    </div>
    <div class="input-group row mb-3">
        <div class="col-2">
            <label asp-for="UserProfile.Alias"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="UserProfile.Alias" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Alias"></span>
    </div>
    <div class="input-group row mb-3">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
        <div class="col">
        </div>
    </div>
</form>

@if (!string.IsNullOrEmpty(Model.SuccessMessage))
{
    <div class="alert alert-success" role="alert">
        @Model.SuccessMessage
    </div>
}